name: Component tests
on: [push, pull_request]
jobs:
  component-test:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.16.0-chrome106-ff99-edge
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Component tests on Chrome
        run: npm run test
